#!/bin/sh
#
# A git hook to make sure user.email and user.mail in repository  exists before committing

global_email=$(git config --global user.email)
global_name=$(git config --global user.name)

repository_email=$(git config user.email)
repository_name=$(git config user.name)

push_url=$(git remote -v | awk '/push/ {print $2}' | head -1)

my_username=`whoami`
repo_user_info_config=`eval echo ~$my_username`"/.git_repo_user_info.conf"
git_repo_user_info=""

if [ -f $repo_user_info_config ]; then
	git_repo_user_info=`cat $repo_user_info_config`
fi

echo $git_repo_user_info

if [ -n "$push_url" ]; then
	ret=""
	echo $git_repo_user_info | awk -v push_url=$push_url -v global_name=$global_name -v global_email=$global_email -v repository_name=$repository_name -v repository_email=$repository_email 'BEGIN {
		default_name = global_name;
		default_email = global_email;

		if (length(default_name) == 0) {
			print "Info : Please use git config --global user.name ur_default_name to set default name";
			exit 1;
		}

		if (length(default_email) == 0) {
			print "Info : Please use git config --global user.email ur_name@ur_company to set default name";
			exit 1;
		}

		name = default_name;
		email = default_email;
	}

	{
		if (push_url ~ "/"$1"/") {
			name = $2;
			email = $3;
		}
	}

	END {
		if (repository_name == name && repository_email == email) {
			exit 0;
		}

		if (length(repository_name) == 0 || repository_name != name) {
			name = (length(name) > 0 ? name : default_name);
		}

		if (length(repository_email) == 0 || repository_email != email ) {
			email = (length(email) > 0 ? email : default_email);
		}

		if (length(name) > 0 && length(email) > 0) {
			cmd = "git config user.name "name";git config user.email "email";";
			print "Info : "cmd;
			system(cmd);
			exit 1;
		}
	}' || ret="1"

	if [ ! -z $ret ]; then
		echo "Pls retry commit"
		exit 1
	fi
fi

if [ -z "$repository_email" ] || [ -z "$repository_name" ] || [ -z "$global_email" ] || [ -z "$global_name" ]; then
    # user.email is empty
    echo "ERROR: [pre-commit hook] Aborting commit because user.email or user.name is missing. Configure them for this repository. Make sure not to configure globally."
    exit 1
else
    # user.email is not empty
    exit 0
fi
